name: edutrack
description: "Aplikasi manajemen tugas untuk siswa/mahasiswa."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  random_string: ^2.3.1
  fluttertoast: ^9.0.0
  firebase_auth: ^6.1.1
  provider: ^6.1.5+1
  intl: ^0.20.2
  syncfusion_flutter_charts: ^31.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/ProductSans-Black.ttf
          weight: 900
        - asset: assets/fonts/ProductSans-BlackItalic.ttf
          weight: 700
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/ProductSans-BoldItalic.ttf
          weight: 600
        - asset: assets/fonts/ProductSans-Italic.ttf
          weight: 400
        - asset: assets/fonts/ProductSans-Light.ttf
          weight: 300
        - asset: assets/fonts/ProductSans-LightItalic.ttf
          weight: 200
        - asset: assets/fonts/ProductSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/ProductSans-MediumItalic.ttf
          weight: 400
        - asset: assets/fonts/ProductSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/ProductSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/ProductSans-ThinItalic.ttf
          weight: 100
