name: EduTrack
description: "Aplikasi manajemen tugas untuk siswa/mahasiswa."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  random_string: ^2.3.1
  fluttertoast: ^9.0.0
  firebase_auth: ^6.1.1
  provider: ^6.1.5+1
  intl: ^0.20.2
  syncfusion_flutter_charts: ^31.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
